// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentApprove(arg1) {
  return window['go']['main']['App']['AgentApprove'](arg1);
}

export function AgentPlan(arg1) {
  return window['go']['main']['App']['AgentPlan'](arg1);
}

export function AgentProjectContext() {
  return window['go']['main']['App']['AgentProjectContext']();
}

export function AgentRun(arg1, arg2) {
  return window['go']['main']['App']['AgentRun'](arg1, arg2);
}

export function AgentRunStream(arg1, arg2) {
  return window['go']['main']['App']['AgentRunStream'](arg1, arg2);
}

export function AgentStream(arg1, arg2) {
  return window['go']['main']['App']['AgentStream'](arg1, arg2);
}

export function AnalyzeProject() {
  return window['go']['main']['App']['AnalyzeProject']();
}

export function ApprovePending(arg1) {
  return window['go']['main']['App']['ApprovePending'](arg1);
}

export function CapabilityState() {
  return window['go']['main']['App']['CapabilityState']();
}

export function CaptureUI(arg1) {
  return window['go']['main']['App']['CaptureUI'](arg1);
}

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function ChatHistory() {
  return window['go']['main']['App']['ChatHistory']();
}

export function ChatStream(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChatStream'](arg1, arg2, arg3, arg4);
}

export function CancelChatStream(arg1) {
  return window['go']['main']['App']['CancelChatStream'](arg1);
}

export function ChatListSessions() {
  return window['go']['main']['App']['ChatListSessions']();
}

export function ChatSessionMessages(arg1) {
  return window['go']['main']['App']['ChatSessionMessages'](arg1);
}

export function CloseProject() {
  return window['go']['main']['App']['CloseProject']();
}

export function ConsumeEvents() {
  return window['go']['main']['App']['ConsumeEvents']();
}

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function DenyPending(arg1) {
  return window['go']['main']['App']['DenyPending'](arg1);
}

export function DetectRoot() {
  return window['go']['main']['App']['DetectRoot']();
}

export function DiffSnapshot() {
  return window['go']['main']['App']['DiffSnapshot']();
}

export function DiscoverProjects(arg1) {
  return window['go']['main']['App']['DiscoverProjects'](arg1);
}

export function HasProject() {
  return window['go']['main']['App']['HasProject']();
}

export function InitProject() {
  return window['go']['main']['App']['InitProject']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function PendingApproval() {
  return window['go']['main']['App']['PendingApproval']();
}

export function PlanDetails(arg1) {
  return window['go']['main']['App']['PlanDetails'](arg1);
}

export function ProjectContext() {
  return window['go']['main']['App']['ProjectContext']();
}

export function ProjectDiff() {
  return window['go']['main']['App']['ProjectDiff']();
}

export function ProjectInfo() {
  return window['go']['main']['App']['ProjectInfo']();
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RefreshProject() {
  return window['go']['main']['App']['RefreshProject']();
}

export function RequestApproval(arg1, arg2, arg3) {
  return window['go']['main']['App']['RequestApproval'](arg1, arg2, arg3);
}

export function RootInfo() {
  return window['go']['main']['App']['RootInfo']();
}

export function RootMode() {
  return window['go']['main']['App']['RootMode']();
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function RunCommandAuthorized(arg1) {
  return window['go']['main']['App']['RunCommandAuthorized'](arg1);
}

export function SubscribeRuntime() {
  return window['go']['main']['App']['SubscribeRuntime']();
}

export function TreeDirs() {
  return window['go']['main']['App']['TreeDirs']();
}

export function ValidateLocation(arg1) {
  return window['go']['main']['App']['ValidateLocation'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
