// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AgentApprove(arg1:string):Promise<string>;

export function AgentPlan(arg1:string):Promise<string>;

export function AgentProjectContext():Promise<Record<string, any>>;

export function AgentRun(arg1:string,arg2:string):Promise<string>;

export function AgentRunStream(arg1:string,arg2:string):Promise<string>;

export function AgentStream(arg1:string,arg2:string):Promise<Array<main.RuntimeEvent>>;

export function AnalyzeProject():Promise<Record<string, any>>;

export function ApprovePending(arg1:string):Promise<main.Approval>;

export function CapabilityState():Promise<Record<string, any>>;

export function CaptureUI(arg1:string):Promise<Record<string, any>>;

export function Chat(arg1:string):Promise<main.ChatMessage>;

export function ChatHistory():Promise<Array<main.ChatMessage>>;

// ── FASE 3 — CHAT (Kernel-First /v1/run/stream) ─────────────────────────────
// Shapado pelo backend (app.go). A UI NÃO tem lógica cognitiva: só consome.

// ChatStreamResult é a resposta consolidada de um turno de conversa.
export interface ChatStreamResult {
  text: string;
  session_id: string;
  model: string;
  provider: string;
  agent: string;
  duration_ms: number;
  ended: "done" | "error" | "cancelled" | string;
  error?: string;
}

// ChatSessionSummary é um resumo leve de uma conversa persistida (sidebar).
export interface ChatSessionSummary {
  id: string;
  title: string;
  model: string;
  messages: number;
  updated_at: string;
}

// Frame canônico do streaming (shape do daemon `data:` re-emitido em
// `cosca:chat:event`). A UI interpreta `type`.
export interface ChatFrame {
  type: "thinking" | "status" | "progress" | "response" | "metadata" | "done" | "error" | "cancelled" | string;
  content?: string;
  status?: string;
  error?: string;
  session_id?: string;
  model?: string;
  provider?: string;
  agent?: string;
  duration_ms?: number;
  token_usage?: Record<string, number>;
  metadata?: Record<string, any>;
}

export function ChatStream(runID:string,message:string,sessionId:string,model:string):Promise<ChatStreamResult>;

export function CancelChatStream(runID:string):Promise<boolean>;

export function ChatListSessions():Promise<Array<ChatSessionSummary>>;

export function ChatSessionMessages(id:string):Promise<Array<main.ChatMessage>>;

export function CloseProject():Promise<void>;

export function ConsumeEvents():Promise<Array<main.RuntimeEvent>>;

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function CreateProject(arg1:string,arg2:string):Promise<main.Project>;

export function DenyPending(arg1:string):Promise<main.Approval>;

export function DetectRoot():Promise<Record<string, any>>;

export function DiffSnapshot():Promise<Record<string, any>>;

export function DiscoverProjects(arg1:string):Promise<Array<main.Project>>;

export function HasProject():Promise<boolean>;

export function InitProject():Promise<main.Project>;

export function OpenProject(arg1:string):Promise<main.Project>;

export function PendingApproval():Promise<main.Approval>;

export function PlanDetails(arg1:string):Promise<Record<string, any>>;

export function ProjectContext():Promise<main.Project>;

export function ProjectDiff():Promise<Record<string, any>>;

export function ProjectInfo():Promise<Record<string, any>>;

export function ReadDir(arg1:string):Promise<Array<main.FileNode>>;

export function ReadFile(arg1:string):Promise<string>;

export function RefreshProject():Promise<Record<string, any>>;

export function RequestApproval(arg1:string,arg2:string,arg3:string):Promise<main.Approval>;

export function RootInfo():Promise<Record<string, any>>;

export function RootMode():Promise<boolean>;

export function RunCommand(arg1:string):Promise<string>;

export function RunCommandAuthorized(arg1:string):Promise<string>;

export function SubscribeRuntime():Promise<Array<main.RuntimeEvent>>;

export function TreeDirs():Promise<Array<main.TreeEntry>>;

export function ValidateLocation(arg1:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
